Repository AY2223S2-CS2113-F13-3/tp, pull requests merged in 2023-03, with the labels that each got.

#20 Add Storage class and StorageTest JUnit test
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: type.Task, priority.High

#26 Update Duke & Expected
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/EventList.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Epic, priority.High

#28 Bugfix - Ui and Parser
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, severity.High

#34 Implement EventListAdapter to serialize/deserialize EventList class & Integrate saving feature
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Event.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/storage/EventListAdapter.java
  src/main/java/seedu/duke/storage/Storage.java
Labels: type.Enhancement, priority Medium

#35 Add JUnit tests for Parser and EventList
  src/test/java/seedu/duke/EventListTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: type.Task, priority Medium
